name: confluent-operator
replicas: 1
image:
  registry: confluentinc
  repository: confluent-control-center
  tag: 6.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort  # Set this to NodePort for external access or ClusterIP for internal only
  nodePort: 30000 # Optional: If NodePort, specify this port (ensure it's available)

webhooks:
  enabled: false   # Whether webhooks are enabled
  port: 8443      # Webhook port

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

serviceAccount:
  create: true  # Set to true if the ServiceAccount should be created by Helm
  name: ""      # Optionally specify a ServiceAccount name, leave blank to use the default name

# Zookeeper configuration
zookeeper:
  enabled: true
  replicas: 1
  config:
    tickTime: 2000
    dataDir: /var/lib/zookeeper/data
    clientPort: 2181
