name: confluent-operator
replicas: 1
image:
  registry: confluentinc
  repository: confluent-control-center
  tag: 6.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort  # Set this to NodePort for external access or ClusterIP for internal only
  nodePort: 30000 # Optional: If NodePort, specify this port (ensure it's available)

webhooks:
  enabled: true   # Whether webhooks are enabled
  port: 8443      # Webhook port

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
serviceAccount:
  create: true  # Set to true if the ServiceAccount should be created by Helm
  name: ""      # Optionally specify a ServiceAccount name, leave blank to use the default name
