server:
  port: 8165

avro:
  topic:
    name: "avroTopic"
  schema:
    path: "classpath:avro/schemas/StudentRecord.avsc"

dlt:
  topic:
    name: "dltTopic"  # DLT topic name for error messages

spring:
  kafka:
    bootstrap-servers: "kafka-deployment.default.svc.cluster.local:9092"
    producer:
      keySerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://my-schema-registry.default.svc.cluster.local:8081"
