server:
  port: 8165

avro:
  topic:
    name: "avroTopic"
  schema:
    path: "classpath:avro/schemas/StudentRecord.avsc"

dlt:
  topic:
    name: "topicForWrongSchema"  # DLT topic name for error messages

spring:
  kafka:
    bootstrap-servers: "kafka-deployment.kafka-infra.svc.cluster.local:9092"
    bootstrap-servers-compose: "172.20.0.1:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            DockerComposeUrl: "http://schema-registry:8081"
            url: "http://my-schema-registry.kafka-infra.svc.cluster.local:8081"
