server:
  port: 8165

avro:
  topic:
    name: "avroTopic"
  schema:
    path: "classpath:avro/schemas/StudentRecord.avsc"  # Relative path in resources folder

spring:
  kafka:
    bootstrap-servers: "kafka-deployment.default.svc.cluster.local:9092"  # Use the service name of your Kafka cluster
    producer:
      keySerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://my-schema-registry.default.svc.cluster.local:8081"  # Use the service name of your Schema Registry
