server:
  port: 8165

avro:
  topic:
    name: "avrotest1"

spring:
  kafka:
    bootstrap-servers: "kafka-deployment.default.svc.cluster.local:9092"  # Use the service name of your Kafka cluster
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://schema-registry:8081"  # Use the service name of your Schema Registry
