apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-producer.fullname" . }}
  labels:
    {{- include "kafka-producer.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8165   # Changed to match the port your application is running on
      targetPort: 8165  # Ensure this is the same as your container port
      protocol: TCP
      name: kafka
  selector:
    {{- include "kafka-producer.selectorLabels" . | nindent 4 }}
