apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-producer.fullname" . }}
  labels:
    {{- include "kafka-producer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9092  # Standard Kafka port
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    {{- include "kafka-producer.selectorLabels" . | nindent 4 }}
