apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/name: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: {{ include "confluent-operator.chart" . }}
    version: 7.4.1
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "confluent-operator"
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "confluent-operator"
        app.kubernetes.io/name: "confluent-operator"
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: 7.4.1
    spec:
      containers:
        - name: {{ .Values.name }}
          image: confluentinc/cp-enterprise-control-center:7.4.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODEIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: "kafka-deployment:9092"  # Kafka broker address
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"  # Set to desired replication factor
            - name: CONTROL_CENTER_KAFKA_BROKERS_EXPECTED_COUNT
              value: "1"  # Expected number of brokers

            # === NEW ENVIRONMENT VARIABLES ADDED FOR CONTROL CENTER ===
            - name: CONTROL_CENTER_KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: "kafka-cluster:9092"  # Updated for Control Center
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: "http://my-schema-registry.default.svc.cluster.local:8081"  # Updated Schema Registry URL
          ports:
            - containerPort: 9021  # Ensure this port matches the service port
