apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/name: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: {{ include "confluent-operator.chart" . }}
    version: {{ .Values.image.tag }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "confluent-operator"
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "confluent-operator"
        app.kubernetes.io/name: "confluent-operator"
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: {{ .Values.image.tag }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{.Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODEIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          # Commenting out the sslcert volumeMount
          # volumeMounts:
          #   - name: sslcert
          #     mountPath: /etc/certificates
      # Commenting out the volumes section
      # volumes:
      #   - name: sslcert
      #     secret:
      #       secretName: confluent-cert
