apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: default
spec:
  replicas: 1
  dataVolumeCapacity: "10Gi"
  image:
    application: "confluentinc/cp-server:7.4.1"  # Specifying image in the required format
    init: "confluentinc/cp-init-container:7.4.1"  # Placeholder for required init container image
