apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: default
  labels:
    app.kubernetes.io/managed-by: "Helm"  # Required by Helm
  annotations:
    meta.helm.sh/release-name: "kafka-producer-release"  # Match the Helm release name
    meta.helm.sh/release-namespace: "default"            # Match the Helm release namespace
spec:
  replicas: 1
  dataVolumeCapacity: "10Gi"
  image:
    application: "confluentinc/cp-server:7.4.1"
    init: "confluentinc/cp-init-container:7.4.1"
