apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: default
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"  # Unique broker ID
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "confluent-for-kubernetes-zookeeper:2181"  # Ensure Zookeeper is correctly set up
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-deployment.default.svc.cluster.local:9092"  # Internal service name for internal access
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"  # Listen on all interfaces
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"  # Replication factor for internal offsets topic
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"  # Minimum in-sync replicas for transaction state log
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"  # Replication factor for transaction state log
