apiVersion: v1
kind: Service
metadata:
  name: kafka-deployment
  namespace: default
spec:
  selector:
    app: kafka  # Ensure this matches the labels in your Kafka Deployment
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
