apiVersion: v1
kind: Service
metadata:
  name: my-schema-registry
  namespace: default
  labels:
    app: my-schema-registry
spec:
  selector:
    app: my-schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort  # Use 'LoadBalancer' or 'NodePort' if you need external access
