apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/name: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: {{ include "confluent-operator.chart" . }}
  name: confluent-operator
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort  # Expose the service externally
  ports:
    - name: control-center  # Updated port name for Control Center
      port: 9021            # Control Center's default port
      targetPort: 9021       # Ensure this matches the container port
      nodePort: 30090       # Specify a static NodePort for external access
  selector:
    app: "confluent-operator"
    app.kubernetes.io/name: "confluent-operator"
