apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/name: {{ include "confluent-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "confluent-operator"
    helm.sh/chart: {{ include "confluent-operator.chart" . }}
  name: confluent-operator
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092  # Standard Kafka port
      protocol: TCP
      targetPort: 9092
  selector:
    app: "confluent-operator"
    app.kubernetes.io/name: "confluent-operator"



