apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "confluent-operator.name" . }}-zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "confluent-operator.name" . }}-zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: "zookeeper"
    helm.sh/chart: {{ include "confluent-operator.chart" . }}
spec:
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      app: {{ include "confluent-operator.name" . }}-zookeeper
  template:
    metadata:
      labels:
        app: {{ include "confluent-operator.name" . }}-zookeeper
    spec:
      containers:
          - name: zookeeper
            image: confluentinc/cp-zookeeper:7.4.1
            ports:
              - containerPort: 2181
            env:
              - name: ZOOKEEPER_CLIENT_PORT
                value: "2181"
              - name: ZOOKEEPER_TICK_TIME
                value: "{{ .Values.zookeeper.config.tickTime }}"
              - name: ZOOKEEPER_DATA_DIR
                value: "{{ .Values.zookeeper.config.dataDir }}"
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"
