apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-cluster
  namespace: default
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "kafka-producer-release"
    meta.helm.sh/release-namespace: "default"
spec:
  replicas: 1
  dataVolumeCapacity: "10Gi"
  logVolumeCapacity: "10Gi"
  image:
    application: "confluentinc/cp-zookeeper:7.4.1"
    init: "confluentinc/cp-init-container:7.4.1"
