apiVersion: v2
name: kafka-producer
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0" # This can be your application's version
dependencies:
  - name: confluent-for-kubernetes
    version: 0.1033.33  # Use the latest stable version available
    repository: "https://packages.confluent.io/helm"
